const ShopActionTypes = {
  FETCH_ITEMS_START: "FETCH_ITEMS_START",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FAILURE: "FETCH_ITEMS_FAILURE",
  GET_ITEMS_BY_CATEGORY: "GET_ITEMS_BY_CATEGORY",
  GET_SINGLE_ITEM: "GET_SINGLE_ITEM",
  GET_ITEMS_FROM_FIREBASE: "GET_ITEMS_FROM_FIREBASE",
};

export default ShopActionTypes;
